# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
