# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rev', '0003_auto_20180729_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
